### ISSUE TITLE
cc_volumecontrol crashed with "AttributeError: 'list' object has no attribute 'wait'"

### ISSUE THREAD

**Issue by brlin-tw** [merklel/chromecast-frontend#4]
```
$ cc_volumecontrol 
([Chromecast('unknown', port=8009, cast_info=CastInfo(services={ServiceInfo(type='mdns', data='Chromecast-Audio-df6d763868f07bd72b58706190be04b9._googlecast._tcp.local.')}, uuid=UUID('df6d7638-68f0-7bd7-2b58-706190be04b9'), model_name='Chromecast Audio', friendly_name='林博仁的 Chromecast Audio', host='192.168.1.207', port=8009, cast_type='audio', manufacturer='Google Inc.'))], <pychromecast.discovery.CastBrowser object at 0x7f6fa10a0d90>)
Traceback (most recent call last):
  File "/home/brlin/.local/bin/cc_volumecontrol", line 6, in <module>
    chromecast_volumecontrol.gui.start_guiapp()
  File "/home/brlin/.local/pipx/venvs/chromecast-volumecontrol/lib/python3.9/site-packages/chromecast_volumecontrol/gui.py", line 142, in start_guiapp
    app.get_and_draw_chromecasts()
  File "/home/brlin/.local/pipx/venvs/chromecast-volumecontrol/lib/python3.9/site-packages/chromecast_volumecontrol/gui.py", line 110, in get_and_draw_chromecasts
    self.slider_frames = [CC_Slider_Frame(self.frame, cc) for cc in self.chromecasts]
  File "/home/brlin/.local/pipx/venvs/chromecast-volumecontrol/lib/python3.9/site-packages/chromecast_volumecontrol/gui.py", line 110, in <listcomp>
    self.slider_frames = [CC_Slider_Frame(self.frame, cc) for cc in self.chromecasts]
  File "/home/brlin/.local/pipx/venvs/chromecast-volumecontrol/lib/python3.9/site-packages/chromecast_volumecontrol/gui.py", line 34, in __init__
    self.cc.wait()
AttributeError: 'list' object has no attribute 'wait'
```

```
OS: Ubuntu 21.10
Python: 3.9.7
chromecast-volumecontrol: 0.0.6 installed via pipx
```

**Comment by merklel** [comment]
Hey brlin,

you're right, thanks. This resulted from an update of chromecast-volumecontrol. Should be fixed now!
